### PR TITLE
Typo: Docker requires one argument

### PR DESCRIPTION
**Pull request by jmn**
(n/t)

### CODE REVIEW

**Comment by alexferl** [comment]
Thanks!

**Comment by jmn** [comment]
Thank you! Following this guide worked beautifully. To use Automatic HTTPS I edited the caddy download link in the Dockerfile to include my DNS provider (Cloudflare) since Caddy doesn't compile that in by default. I added the environment variables described in https://caddyserver.com/docs/automatic-https with the ENV directive in the Dockerfile. Great work!

**Comment by alexferl** [comment]
That's great to know! I might extend to guide to mention that. Thank you.

**Comment by jmn** [comment]
I can also report that changing the version of `image: mattermost/mattermost-prod-app:3` and `image: mattermost/mattermost-prod-db:3` to `3.5.1` (currently latest stable) works great.

**Pull request merged**
